# Introduction {-}

A large variety of microorganisms live within the human body, constituting the "human microbiome." Despite representing on average just 2% of the human body's mass, these microbes play an important role in human health, outnumbering human cells at a ratio of almost ten to one (NIH 2012). While they often serve mutualistic roles, many microorganisms are also associated with various kinds of disease.

In collaboration with Dr. Tony Sung and Alex Sibley in the Duke University School of Medicine, we made use of data collected from the Memorial Sloan Kettering Cancer Center on patients recovering from blood cancer. These individuals had all been diagnosed with some form of leukemia, and had then been provided with stem cell transplants in an effort to combat the cancerous blood cells. These individuals also recovered after their transplants in different locations, including houses, apartments, and clinics.

Throughout the treatment process, stool samples were supplied by the patients. These samples were then sequenced by Memorial Sloan Kettering. The goal of this study, using these microbial sequencing data, was threefold: 1) better understand the filtration process that goes into the processing, filtration, and cleaning of microbiome sequencing data. 2) devise effective, interactive visualizations for the dynamics of microbiome compositions. 3) apply statistical methodology to identify potential associations between factors in recovery from leukemia and the microbiome.